### ISSUE TITLE
Relationship between cxtypes.go and cxcore.go

### ISSUE THREAD

**Issue by JKhawaja** [lazywei/go-opencv#10]
Hi,

I was wondering what the relationship between the types file and the core file is? Is one holding the OpenCV Basic Structures and 'core' is holding all related methods? (on second thought they are both holding their own share of methods, etc.) ...

Actually, I am just trying to get a neat overview of how this project is being organized. :)

**Comment by lazywei** [comment]
sorry but i don't plan to maintain the v1 API anymore. i'm going to target v2 (i.e. C++ API) in the future :D 
please let me know if you have any other concern.
Thanks.
