### ISSUE TITLE
Problem in myGetMatType?

### ISSUE THREAD

**Issue by mcqueenorama** [lazywei/go-opencv#28]
I've found that when I pull the type out of an image and try to use it, its way out of bounds.  If I use the static value opencv.IPL_DEPTH_8U, it works.  Here's a line of output from a test run where I'm printing out the values of a call to GetImage:

channels:3:Rows:512:Cols:512:Type:1111638032:opencv.IPL_DEPTH_8U:8:

If you take the mat from an image in hellocv.go, then try to get the image from the mat it will crash, due to the type being a crazy number.  I'm sure its due to the complicated union business.  I hope you know how to fix it.  It would take me a long time to figure it out.

Here's the function that printed the above line, taken from cxcore.go:

/* GetImage returns the image header for the matrix. */
func (m *Mat) GetImage(channels int) *IplImage {

	fmt.Printf("channels:%v:Rows:%v:Cols:%v:Type:%v:opencv.IPL_DEPTH_8U:%v:\n", channels, m.Rows(), m.Cols(), m.Type(), IPL_DEPTH_8U)

        //swapping these two lines fixes the problem
	//tmp := CreateImage(m.Cols(), m.Rows(), IPL_DEPTH_8U, channels)
	 tmp := CreateImage(m.Cols(), m.Rows(), m.Type(), channels)

        //the above line crashes 
        //m.Type() has got a crazy value

	img := C.cvGetImage(unsafe.Pointer(m), (*C.IplImage)(tmp))

	return (*IplImage)(img)
}

Add these lines to hellocv.go under the line "defer image.Release()" to reproduce it:

	mat2 := image.GetMat()
	defer mat2.Release()

	channels := image.Channels()

	imgHeader := mat2.GetImage(channels)
	if imgHeader == nil {
		panic("GetImage fail")
	}

**Comment by lazywei** [comment]
sorry but i don't plan to maintain the v1 API anymore. i'm going to target v2 (i.e. C++ API) in the future :D 
please let me know if you have any other concern.
Thanks.

**Comment by mcqueenorama** [comment]
Sounds good.  I want the C++ API anyway.  BTW by coincidence, I discovered that a guy I know at the gym is one of the leaders of the opencv project.  I had no idea.

**Comment by lazywei** [comment]
wow... that's pretty good. do you think he will be interested in this project :-P ?

**Comment by mcqueenorama** [comment]
Maybe so.  I'll check.  It was a funny coincidence.
