### ISSUE TITLE
Ability to crop an image

### ISSUE THREAD

**Issue by peterbe** [lazywei/go-opencv#32]
I like the resize function but what I need is to also be able to crop. Something like
```go
image := opencv.LoadImage(args[0])
cropped := opencv.Crop(image, 100, 100, 400, 400)
```

**Comment by lazywei** [comment]
sorry but i don't plan to maintain the v1 API anymore. i'm going to target v2 (i.e. C++ API) in the future :D 
please let me know if you have any other concern.
I think we may add the wrapper for this in C++ API later.
Thanks.
