### ISSUE TITLE
Issue with NewCameraCapture()

### ISSUE THREAD

**Issue by JulianGindi** [lazywei/go-opencv#36]
I am having a strange issue when attempting to call NewCameraCapture().

I have a function takePhoto() when ran by itself, works fine. When I have the same function in a loop that waits for a goroutine to return data over a channel, it just hangs without any error message.

I believe the line that is causing my problems is [this one](https://github.com/lazywei/go-opencv/blob/6edfcc9d34db33a3d253c66731124055961287e9/opencv/highgui.go#L479). Any guidance on this would be greatly appreciated. I will continue to dig and submit a PR if I find a solution.

**Comment by JulianGindi** [comment]
I'm gonna bump this. Anyone having similar issues, or any suggestions on how I can fix this issue?

**Comment by lazywei** [comment]
sorry but i don't plan to maintain the v1 API anymore. i'm going to target v2 (i.e. C++ API) in the future :D 
please let me know if you have any other concern.
Thanks.
