### ISSUE TITLE
Automatically Release() objects

### ISSUE THREAD

**Issue by unixpickle** [lazywei/go-opencv#37]
I notice that many exported types have a `Release()` method. In a garbage collected language like Go, this feels a little redundant. Why not use `runtime.SetFinalizer()` to automatically free underlying OpenCV objects when the corresponding Go objects become unreachable?

Generally, hiding memory allocation and deallocation from the user makes the library safer to use. Furthermore, it prevents the user from writing code with memory leaks.

I understand that memory usage and performance may be factors here. In that case, perhaps the Release() methods can remain available but will be called automatically be the garbage collector if the user did not call them sooner.

**Comment by lazywei** [comment]
sorry but i don't plan to maintain the v1 API anymore. i'm going to target v2 (i.e. C++ API) in the future :D 
please let me know if you have any other concern.
Thanks.
