### ISSUE TITLE
"could not determine kind of name for C.cvCeil / C.cvFloor / C.cvIsInf / C.cvIsNaN / C.cvRound"

### ISSUE THREAD

**Issue by filiptc** [lazywei/go-opencv#64]
When running `go run hellocv.go`, I get:
```
# github.com/lazywei/go-opencv/opencv
could not determine kind of name for C.cvCeil
could not determine kind of name for C.cvFloor
could not determine kind of name for C.cvIsInf
could not determine kind of name for C.cvIsNaN
could not determine kind of name for C.cvRound
```

Posting `gcc -v` output too, just in case.
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
```

**Comment by filiptc** [comment]
Error fixed by using latest version 2.X (was using 3.X).

**Comment by lazywei** [comment]
Awesome! Thanks for reporting!
Philip Thomas Casado <notifications@github.com>於 2016年1月22日 週五，下午7:16寫道：

> Error fixed by using latest version 2.X (was using 3.X).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lazywei/go-opencv/issues/64#issuecomment-173884890>.
>
-- 
Chih-Wei (Bert)

**Comment by chenziliang** [comment]
@lazywei  Any plan to support opencv 3.X?

**Comment by OhXiwang** [comment]
还在学习中，很感兴趣
Sent from Outlook Mobile




On Sun, Feb 28, 2016 at 4:15 AM -0800, "Ken" <notifications@github.com> wrote:





@lazywei  Any plan to support opencv 3.X?

---

**Comment by lazywei** [comment]
@chenziliang The strategy to add supporting 2.X and 3.X should be similar --- by using SWIG. I'd try to do so when I find a suitable time.
That being said, wrapping the API requires fully understanding of the header files, and I'm not really familiar with C++, which means some of the advanced syntax used in the header files is hard for me to understand. Therefore, it would be great to have some C++ expert to join this project as collaborator.
Please feel free to let me know if you have any interest in this.

Thanks.

**Comment by chenziliang** [comment]
@lazywei  Sure. I have several years c++ background. Let's get into it. Let's get bridged first. Your twitter ?

**Comment by lazywei** [comment]
@chenziliang awesome! i've sent you an email, please check it out and let me know your thougts. thanks

**Comment by Kabariya** [comment]
this post was posted in 2016 and I am still getting the same error... Any solution

**Comment by Archie1978** [comment]
Hello,

 I have a same problem:
# github.com/lazywei/go-opencv/opencv
../../../github.com/lazywei/go-opencv/opencv/cxtype.go:157:8: could not determine kind of name for C.cvCeil
../../../github.com/lazywei/go-opencv/opencv/cxtype.go:153:8: could not determine kind of name for C.cvFloor
../../../github.com/lazywei/go-opencv/opencv/cxtype.go:166:8: could not determine kind of name for C.cvIsInf
../../../github.com/lazywei/go-opencv/opencv/cxtype.go:162:8: could not determine kind of name for C.cvIsNaN
../../../github.com/lazywei/go-opencv/opencv/cxtype.go:149:8: could not determine kind of name for C.cvRound


opencv 3.2.0 from ubuntu 18.04
go version go1.12.4 linux/amd64
