### ISSUE TITLE
bitwise_and

### ISSUE THREAD

**Issue by fredcarle** [lazywei/go-opencv#78]
I looked through the source files and can't seem to find the implementation/binding of the opencv bitwise_and function. Is there any plan to make it part of the go package?

**Comment by kevinabrandon** [comment]
I'll do it

**Comment by kevinabrandon** [comment]
Give it a try.  Note there are 4 bitwise And functions:
 - And() - bitwise_and between two images
 - AndScalar() - bitwise_and between an image and a scalar
 - AndWithMask() - bitwise_and between two images using a mask
 - AndScalarWithMask() - bitwise_and between an image and a scalar using a mask
See the tests for examples

**Comment by fredcarle** [comment]
Thanks a lot @kevinabrandon! I'll give it a try later today. Much appreciated.
