### ISSUE TITLE
AbsDiff array type error

### ISSUE THREAD

**Issue by fredcarle** [lazywei/go-opencv#82]
I'm trying to call opencv.AbsDiff() with two grayscale images and when I run the code, I get the following error: 

`OpenCV Error: Bad argument (Unknown array type) in cvarrToMat, file /opencv/location/opencv-2.4.13/modules/core/src/matrix.cpp, line 698`

Any idea as to why that might happen?

Let me know if you need more information.

**Comment by kevinabrandon** [comment]
I just took a look at the AbsDiff() and also added the scalar version.  I added a couple of simple tests and they all seemed to work.  The tests I added are here: https://github.com/lazywei/go-opencv/blob/master/opencv/cxcore_test.go#L327

I would verify that all the images (both src and dst) are the same size, have the same number of channels, and have the same depth - although I would expect a different error message for these.  

I'm about to go on vacation for the week, so good luck.

**Comment by fredcarle** [comment]
Thanks a lot @kevinabrandon. I'll give it a try and see if I can make it work. Have a great vacation!

**Comment by fredcarle** [comment]
Actually, I just tested it again and it works. Like you stated, I had to make sure both the src and dst were the same size and had the same number of channels. I modified my dst to comply to this and it works just fine. 

Again, thanks so much for your time @kevinabrandon.
