### ISSUE TITLE
failed to run sample on raspberry pi

### ISSUE THREAD

**Issue by sangshuduo** [lazywei/go-opencv#87]
on Ubuntu 16.04 armhf.

$ go run hellocv.go
# github.com/lazywei/go-opencv/opencv

/usr/bin/ld: $WORK/github.com/lazywei/go-opencv/opencv/_obj/cxtype.cgo2.o: undefined reference to symbol 'lrint@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by lazywei** [comment]
Hi @sangshuduo 
@didrocks has committed a change on the building flags on arm at #92. Could you check whether this issue can be solved with this patch on your end?

Thanks.
